def gv

pipeline {
    agent any
    parameters {
        choice(name: 'VERSION', choices:['1.1.0','1.2.0','1.3.0'], description:'')
        booleanParam(name: 'executeTests', defaultValue: true, description: '')
    }
    stages{
        stage("code clone"){
            steps{
                echo 'Git repo cloning in progress..'
                git branch: 'main' url: 'https://github.com/send2durai/terraform_sharelibs.git'
            }
        }
        stage("build"){
            steps{
                echo "building the applications...."
                script{
                    sh 'pwd'
                    gv = load "tf.groovy"
                }
            }
        }
        stage("test"){
            when{
                expression {
                    params.executeTests
                }
            }
            steps{
                script{
                    gv.tfplan()
                }
            }
        }
        stage("deploy"){
            steps{
                script {
                    gv.tfapply()
                }
            }
        }
        stage('Workspace Cleanup'){
            steps{
                sh '''
                   echo "Cleaning the Jenkins Workspace"
                '''
                cleanWs()
            }
        }
    }
}
